# Generated by Django 4.2.7 on 2025-12-19 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, help_text='ID único del artículo en la API externa', unique=True)),
                ('title', models.CharField(help_text='Título del artículo', max_length=500)),
                ('url', models.URLField(help_text='URL del artículo original', max_length=1000)),
                ('news_site', models.CharField(help_text='Sitio de noticias que publicó el artículo', max_length=200)),
                ('sentiment_score', models.IntegerField(default=0, help_text='1 si contiene Mars/Moon, 0 en otro caso')),
                ('published_at', models.DateTimeField(db_index=True, help_text='Fecha de publicación del artículo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación en nuestra DB')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se marcó como favorito')),
                ('article', models.ForeignKey(help_text='Artículo marcado como favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='articles.article')),
                ('user', models.ForeignKey(help_text='Usuario que marcó el artículo como favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at', 'news_site'], name='articles_ar_publish_9d552c_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'created_at'], name='articles_fa_user_id_1a450e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'article')},
        ),
    ]
